import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.REACT_APP_SUPABASE_URL
const supabaseAnonKey = process.env.REACT_APP_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// ── Plant seed data from her spreadsheet ──────────────────────
export const SEED_PLANTS = [
  // Nightshades
  { name: 'Corn (Pole Tomato)', variety: 'Beefstock', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '4-6 weeks before frost', direct_sow_timing: 'Transplant 1-2 weeks after frost', days_to_harvest: '96', in_ground_start: 'May 1st', seed_quantity: '25 seeds', notes: null },
  { name: 'Roma Tomato', variety: 'Italian Roma', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '4-6 weeks before frost', direct_sow_timing: 'Transplant 1-2 weeks after frost', days_to_harvest: '80', in_ground_start: 'May 1st', seed_quantity: '25 seeds', notes: null },
  { name: 'Tomato', variety: 'Heirloom', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '6-8 weeks before frost', direct_sow_timing: '1 week after frost', days_to_harvest: '82', in_ground_start: 'May 1st', seed_quantity: '1/10 gram', notes: null },
  { name: 'Cherry Tomato', variety: 'Cherry', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '6-8 weeks before frost', direct_sow_timing: '1 week after frost', days_to_harvest: '65', in_ground_start: 'May 1st', seed_quantity: '1/10 gram', notes: 'Trellis, center of row' },
  { name: 'Sweet Pepper Red/Green', variety: 'California Wonder', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '8-10 weeks before frost', direct_sow_timing: 'Transplant 2-4 weeks after frost', days_to_harvest: '75 from transplanting', in_ground_start: 'May 1st', seed_quantity: '30 seeds', notes: 'Red and green color' },
  { name: 'Sweet Pepper Yellow', variety: 'Golden Cal Wonder', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '8-10 weeks before frost', direct_sow_timing: 'Transplant 2-4 weeks after frost', days_to_harvest: '75 from transplanting', in_ground_start: 'May 1st', seed_quantity: '20 seeds', notes: 'Green to yellow with tint of orange' },
  { name: 'Sweet Pepper Red', variety: 'California Wonder', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '6-8 weeks before frost', direct_sow_timing: null, days_to_harvest: '60 green / 80 red', in_ground_start: 'May 1st', seed_quantity: '1/64 ounce', notes: null },
  { name: 'Hot Pepper', variety: 'Jalapeño Early', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '8 weeks before frost', direct_sow_timing: 'After frost', days_to_harvest: '72-75', in_ground_start: 'May 1st', seed_quantity: '1.2g', notes: 'Harden outside for a week before transplanting' },
  { name: 'Hot Pepper', variety: 'Jalapeño Gigantia', family: 'Nightshades (Solanaceae)', category: 'vegetable', sow_indoors_timing: '8 weeks before frost', direct_sow_timing: 'After frost', days_to_harvest: '70', in_ground_start: 'May 1st', seed_quantity: '170mg', notes: 'Harden outside for a week before transplanting' },
  // Brassicas
  { name: 'Kale', variety: 'Premier', family: 'Brassicas (Cruciferae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'Early spring', days_to_harvest: '55-65', in_ground_start: 'Early spring', in_ground_end: 'Mid-summer', seed_quantity: '2g', notes: null },
  { name: 'Bok Choy', variety: 'White Stem', family: 'Brassicas (Cruciferae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'Early spring', days_to_harvest: '50', in_ground_start: 'Early spring', seed_quantity: '50mg', notes: null },
  { name: 'Collards', variety: 'Georgia', family: 'Brassicas (Cruciferae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'Early spring', days_to_harvest: '65', in_ground_start: 'Early spring', in_ground_end: 'Mid-summer', seed_quantity: '3g', notes: null },
  // Legumes
  { name: 'Bush Bean', variety: 'Jade', family: 'Legumes (Fabaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'Right after no frost danger', days_to_harvest: '55', in_ground_start: 'Frost date', seed_quantity: '1 ounce', notes: null },
  { name: 'Pole Bean', variety: 'Kentucky Wonder', family: 'Legumes (Fabaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: '63', in_ground_start: 'Frost date', seed_quantity: '25g', notes: 'Succession planting 7-14 days until mid-Aug' },
  // Cucurbits
  { name: 'Squash Yellow', variety: "Max's Gold", family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: '55', in_ground_start: 'May 1st', seed_quantity: '12 seeds', notes: null },
  { name: 'Squash Green', variety: 'Black Beauty', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: '55', in_ground_start: 'May 1st', seed_quantity: '4g', notes: null },
  { name: 'Zucchini', variety: 'Cocozelle', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: '3-4 weeks before frost', direct_sow_timing: '1 week after frost', days_to_harvest: '58', in_ground_start: null, seed_quantity: '1/8 ounce', notes: 'Center of bed' },
  { name: 'Cucumber', variety: 'Marketmore', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: '2-4 weeks before frost', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: '60', in_ground_start: 'May 1st', seed_quantity: '1.5g', notes: 'Sows up to 20ft of trellised cucumbers' },
  { name: 'Cucumber', variety: 'Green Finger', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: '3-4 weeks before frost', direct_sow_timing: '1 week after frost', days_to_harvest: null, in_ground_start: 'May 1st', seed_quantity: '1/16 ounce', notes: 'One row in center of bed, 6-10in tall' },
  { name: 'Cucumber', variety: 'National Pickling', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: '3-4 weeks before frost', direct_sow_timing: '1 week after frost', days_to_harvest: null, in_ground_start: 'May 1st', seed_quantity: '1/16 ounce', notes: 'One row in center of bed, 5-6in long' },
  { name: 'Cantaloupe', variety: "Hale's Best Jumbo", family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: '85', in_ground_start: 'May 1st', seed_quantity: '1g', notes: null },
  { name: 'Watermelon', variety: 'Sugar Baby', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: '80', in_ground_start: 'May 1st', seed_quantity: '1.5g', notes: null },
  { name: 'Watermelon', variety: 'Blacktail', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'April 1st', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: '76', in_ground_start: 'May 1st', seed_quantity: '1/16 ounce', notes: 'One row in center of bed or hills, 8in across' },
  { name: 'Pumpkin', variety: "Jack O'Lantern", family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '2-4 weeks after frost', days_to_harvest: '105', in_ground_start: 'May 1st', seed_quantity: '4g', notes: null },
  { name: 'Pumpkin', variety: 'Jack Be Little', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: '95', in_ground_start: 'May 1st', seed_quantity: '1/8 ounce', notes: '3in wide x 2in tall' },
  { name: 'Pumpkin', variety: 'Cinderella', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'After frost', days_to_harvest: '100', in_ground_start: 'May 1st', seed_quantity: '1/8 ounce', notes: 'One row in the center of bed, 5-8 pounds' },
  { name: 'Pumpkin', variety: 'Small Sugar', family: 'Cucurbits (Cucurbitaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'After frost', days_to_harvest: '100', in_ground_start: 'May 1st', seed_quantity: '2.2g', notes: '5-8 pounds' },
  // Alliums
  { name: 'Bunching Onion', variety: 'Parade', family: 'Alliums (Amaryllidaceae)', category: 'vegetable', sow_indoors_timing: '8-10 weeks before frost', direct_sow_timing: 'Workable soil', days_to_harvest: '70', in_ground_start: 'March 1st', seed_quantity: '100 seeds', notes: null },
  // Umbellifers
  { name: 'Carrot', variety: 'Scarlet', family: 'Umbellifers (Apiaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '2-4 weeks before frost', days_to_harvest: '65', in_ground_start: 'March 15 - April 1', seed_quantity: '800mg', notes: null },
  // Asteraceae
  { name: 'Iceberg Lettuce', variety: 'Crispino', family: 'Asteraceae', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'Last frost', days_to_harvest: '57', in_ground_start: 'Frost date', in_ground_end: 'Late summer', seed_quantity: '1/32 ounce', notes: 'Sow every 3 weeks from spring to late summer' },
  { name: 'Romaine Lettuce', variety: 'Parris Island Cos', family: 'Asteraceae', category: 'vegetable', sow_indoors_timing: '4-6 weeks before frost', direct_sow_timing: '2-4 weeks before frost', days_to_harvest: '21-68', in_ground_start: 'April 1st', in_ground_end: 'Sept 1st', seed_quantity: '2g', notes: 'Frost tolerant, 10-12in' },
  { name: 'Spinach', variety: 'Bloomsdale', family: 'Asteraceae', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: '4-6 weeks before frost', days_to_harvest: '28-45', in_ground_start: 'March 15', in_ground_end: 'Sept 1', seed_quantity: '3g', notes: 'Frost tolerant, good for container' },
  { name: 'Spinach', variety: 'Salad Sensation', family: 'Asteraceae', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'Early spring', days_to_harvest: '22-55', in_ground_start: 'Early spring', in_ground_end: 'Mid-summer', seed_quantity: '2.5g', notes: null },
  { name: 'Sunflower', variety: 'Lemon Queen', family: 'Asteraceae', category: 'flower', sow_indoors_timing: 'Not recommended', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: null, in_ground_start: 'May 1st', seed_quantity: '1.5g', notes: "5-7ft tall, succession 2-4 weeks until July" },
  { name: 'Sunflower', variety: 'Sunny Bouquet', family: 'Asteraceae', category: 'flower', sow_indoors_timing: 'Not recommended', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: null, in_ground_start: 'May 1st', seed_quantity: '3g', notes: null },
  // Corn
  { name: 'Corn', variety: 'Buttergold Sweet', family: 'Corn (Poaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'Sow seed 1-2 weeks after frost', days_to_harvest: '63', in_ground_start: 'May 1st', in_ground_end: 'June 1st', seed_quantity: '10g', notes: null },
  { name: 'Corn', variety: 'Honey and Cream', family: 'Corn (Poaceae)', category: 'vegetable', sow_indoors_timing: 'Not recommended', direct_sow_timing: 'Sow seed 1-2 weeks after frost', days_to_harvest: '63', in_ground_start: 'May 1st', in_ground_end: 'June 1st', seed_quantity: '10g', notes: null },
  // Other
  { name: 'Zinnia', variety: 'California Giants', family: 'Other / Flower', category: 'flower', sow_indoors_timing: '4-6 weeks before frost', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: null, in_ground_start: 'May 1st', seed_quantity: '1.5g', notes: "24-48in tall, blooms to frost" },
  { name: 'Zinnia', variety: 'Cut and Come Again', family: 'Other / Flower', category: 'flower', sow_indoors_timing: '4-6 weeks before frost', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: null, in_ground_start: 'May 1st', seed_quantity: '4g', notes: "18-30in tall, blooms to frost" },
  { name: 'Morning Glory', variety: 'Something Old/New', family: 'Other / Flower', category: 'flower', sow_indoors_timing: '4-6 weeks before frost', direct_sow_timing: '1-2 weeks after frost', days_to_harvest: null, in_ground_start: 'May 1st', seed_quantity: '6g', notes: "8-15ft vines, blooms to frost" },
  { name: 'Catnip', variety: 'Nepeta', family: 'Other / Flower', category: 'herb', sow_indoors_timing: '6-8 weeks before frost', direct_sow_timing: '2-4 weeks before frost', days_to_harvest: null, in_ground_start: 'April 1st', seed_quantity: '350mg', notes: null },
]
